spring:
  application:
    name: distributed_payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
