CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    amount NUMERIC(38, 2),
    currency VARCHAR(255),
    status VARCHAR(255),
    idempotency_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT payments_idempotency_key_unique UNIQUE (idempotency_key)
);
